<a href="https://colab.research.google.com/github/LasyaJangapelli-bit/DAA-practical01-8847/blob/main/DAA_Practical06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Algorithm: Cross Matrix Multiplication

In [4]:
import numpy as np

def get_matrix_input(rows, cols, name):
    """Gets matrix input from the user."""
    matrix = []
    print(f"Enter elements for {name} ({rows}x{cols}):")
    for i in range(rows):
        while True:
            try:
                row_str = input(f"Enter space-separated elements for row {i+1}: ")
                row = list(map(float, row_str.split()))
                if len(row) == cols:
                    matrix.append(row)
                    break
                else:
                    print(f"Error: Row must contain {cols} elements. Please try again.")
            except ValueError:
                print("Error: Invalid input. Please enter numbers only.")
    return np.array(matrix)

def cross_matrix_multiplication(matrix_a, matrix_b):
    """Performs cross matrix multiplication (dot product)."""
    # NumPy's @ operator performs matrix multiplication
    return matrix_a @ matrix_b

# Get dimensions for Matrix A
while True:
    try:
        rows_a = int(input("Enter the number of rows for Matrix A: "))
        cols_a = int(input("Enter the number of columns for Matrix A: "))
        break
    except ValueError:
        print("Invalid input. Please enter an integer.")

# Get dimensions for Matrix B
while True:
    try:
        rows_b = int(input("Enter the number of rows for Matrix B: "))
        cols_b = int(input("Enter the number of columns for Matrix B: "))
        break
    except ValueError:
        print("Invalid input. Please enter an integer.")

# Check if matrices can be multiplied
if cols_a != rows_b:
    print("Error: Number of columns in Matrix A must be equal to the number of rows in Matrix B for cross multiplication.")
else:
    # Get matrix elements from user
    matrix_a = get_matrix_input(rows_a, cols_a, "Matrix A")
    matrix_b = get_matrix_input(rows_b, cols_b, "Matrix B")

    # Perform multiplication
    result_matrix = cross_matrix_multiplication(matrix_a, matrix_b)

    print("\nMatrix A:")
    print(matrix_a)
    print("\nMatrix B:")
    print(matrix_b)
    print("\nResult of Cross Matrix Multiplication:")
    print(result_matrix)


Enter the number of rows for Matrix A: 4
Enter the number of columns for Matrix A: 3
Enter the number of rows for Matrix B: 3
Enter the number of columns for Matrix B: 4
Enter elements for Matrix A (4x3):
Enter space-separated elements for row 1: 0 4 5 4
Error: Row must contain 3 elements. Please try again.
Enter space-separated elements for row 1: 0 5 4
Enter space-separated elements for row 2: 0 2 8
Enter space-separated elements for row 3: 7 8 9
Enter space-separated elements for row 4: 2 4 6
Enter elements for Matrix B (3x4):
Enter space-separated elements for row 1: 2 5 6 7
Enter space-separated elements for row 2: 0 5 6 9
Enter space-separated elements for row 3: 1 5 7 2

Matrix A:
[[0. 5. 4.]
 [0. 2. 8.]
 [7. 8. 9.]
 [2. 4. 6.]]

Matrix B:
[[2. 5. 6. 7.]
 [0. 5. 6. 9.]
 [1. 5. 7. 2.]]

Result of Cross Matrix Multiplication:
[[  4.  45.  58.  53.]
 [  8.  50.  68.  34.]
 [ 23. 120. 153. 139.]
 [ 10.  60.  78.  62.]]
